# Generated by Django 4.2.3 on 2023-07-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='primary_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
