# Generated by Django 4.2.3 on 2023-07-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0003_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, default=0, verbose_name='age'),
        ),
        migrations.AlterField(
            model_name='user',
            name='local_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='local name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='primary_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Primary phone number'),
        ),
    ]
