# Generated by Django 4.2.3 on 2023-07-05 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_logo', models.ImageField(blank=True, null=True, upload_to='product/images/', verbose_name='Product Logo')),
                ('product_name', models.CharField(max_length=100, verbose_name='Product')),
                ('product_description', models.CharField(max_length=500, verbose_name='Product Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('product_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productmanager.producttype', verbose_name='Product Type')),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_type', models.CharField(choices=[('M', 'Monthly'), ('A', 'Annual'), ('L', 'Lifetime')], default='Lifetime', max_length=100)),
                ('number', models.IntegerField(default=0, verbose_name='Number')),
                ('valid_date', models.DateTimeField(blank=True, verbose_name='Valid Date')),
                ('expired_date', models.DateTimeField(blank=True, verbose_name='Expired Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productmanager.product', verbose_name='Product ID')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(blank=True, max_length=100, verbose_name='Device Name')),
                ('ip_address', models.CharField(blank=True, max_length=100, verbose_name='IP Address')),
                ('mac_address', models.CharField(blank=True, max_length=30, verbose_name='MAC Address')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('license_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productmanager.license', verbose_name='License ID')),
            ],
        ),
    ]
