# Generated by Django 4.2.3 on 2023-07-05 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='product_key',
            field=models.CharField(blank=True, editable=False, max_length=50, unique=True, verbose_name='Product Key'),
        ),
    ]
