# Generated by Django 4.2.3 on 2023-07-05 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productmanager', '0002_license_product_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='expired_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expired Date'),
        ),
    ]
